name: Run Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-example:
    name: Test / Run Example
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          - "ubuntu-latest"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install Poetry
        run: |
          pipx install poetry==1.8.2

      - name: Install Dependencies
        run: |
          sudo rm -f /etc/apt/sources.list.d/archive_uri-*
          sudo apt-get update
          sudo apt-get install -y xorg-dev libglu1-mesa-dev

      - name: Build evogym
        run: |
          echo "Python Version: $(python --version)"
          echo "Poesy Version: $(poetry --version)"
          poetry install --no-root
          poetry build && poetry run python setup.py install

      - name: Run Example
        run: |
          cd examples
          poetry run python gym_test_without_render.py
