name: Testing

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          - "ubuntu-latest"
        python:
          - "3.8"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version

      - name: Install Poetry
        run: |
          pipx install poetry==1.8.2

      - name: Install Dependencies
        run: |
          sudo rm -f /etc/apt/sources.list.d/archive_uri-*
          sudo apt-get update
          sudo apt-get install -y xorg-dev libglu1-mesa-dev xvfb

      - name: Build evogym
        run: |
          echo "Python Version: $(python --version)"
          echo "Poesy Version: $(poetry --version)"
          poetry install --no-root
          poetry build && poetry run python setup.py install

      - name: Run test
        run: xvfb-run python -m unittest tests/test_render.py
